using System;
using System.Linq;
using System.Text;
using LadderToArduino.Models;

namespace LadderToArduino.Services
{
    // Converts a LadderProgram into a compilable Arduino .ino sketch.
    // Model: each rung = OR of branches, each branch = AND of contacts, feeding one or more output elements.
    // Timers use millis() based on-delay/off-delay, with an optional external reset.
    // Counters count rising edges of the rung result, with an optional external reset.
    // Analog inputs feed a comparator contact; Analog (PWM) outputs write 0-255 while their rung is true.
    // The sketch also prints a compact state line over Serial every ~150ms for the app's live Monitor tab.
    public static class CodeGenerator
    {
        public static string Generate(LadderProgram program, string sketchName)
        {
            int inputCount = SizeFor(program, AddressKind.Input);
            int outputCount = SizeFor(program, AddressKind.Output);
            int memoryCount = SizeFor(program, AddressKind.Memory);
            int timerCount = SizeFor(program, AddressKind.Timer);
            int counterCount = SizeFor(program, AddressKind.Counter);
            int analogInCount = SizeFor(program, AddressKind.AnalogInput);
            int pwmOutCount = SizeFor(program, AddressKind.PWMOutput);

            var sb = new StringBuilder();
            sb.AppendLine($"// {sketchName}.ino");
            sb.AppendLine("// Auto-generated by LadderToArduino - do not hand edit unless you know what you're doing.");
            sb.AppendLine("// Ladder model: rung = OR(branches), branch = AND(contacts) -> one or more output elements.");
            sb.AppendLine();
            sb.AppendLine("#include <Arduino.h>");
            sb.AppendLine();

            sb.AppendLine($"bool I[{Math.Max(inputCount, 1)}];    // physical digital inputs");
            sb.AppendLine($"bool Q[{Math.Max(outputCount, 1)}];    // physical digital outputs");
            sb.AppendLine($"bool M[{Math.Max(memoryCount, 1)}];    // internal memory bits");
            sb.AppendLine($"int  AI[{Math.Max(analogInCount, 1)}]; // analogRead() results (0-1023)");
            sb.AppendLine();
            sb.AppendLine("struct TimerState { bool running; unsigned long start; unsigned long preset; bool q; bool offRunning; };");
            sb.AppendLine($"TimerState T[{Math.Max(timerCount, 1)}];");
            sb.AppendLine();
            sb.AppendLine("struct CounterState { long count; long preset; bool lastIn; bool q; };");
            sb.AppendLine($"CounterState C[{Math.Max(counterCount, 1)}];");
            sb.AppendLine();
            sb.AppendLine($"const unsigned long SCAN_DELAY_MS = {program.ScanDelayMs};");
            sb.AppendLine("unsigned long lastStatePrint = 0;");
            sb.AppendLine();

            var inputPins = program.PinMap.Where(p => p.Kind == AddressKind.Input).OrderBy(p => p.Index).ToList();
            var outputPins = program.PinMap.Where(p => p.Kind == AddressKind.Output).OrderBy(p => p.Index).ToList();
            var analogInPins = program.PinMap.Where(p => p.Kind == AddressKind.AnalogInput).OrderBy(p => p.Index).ToList();
            var pwmOutPins = program.PinMap.Where(p => p.Kind == AddressKind.PWMOutput).OrderBy(p => p.Index).ToList();

            sb.AppendLine("void setup() {");
            sb.AppendLine("  Serial.begin(9600);");
            foreach (var p in inputPins)
                sb.AppendLine($"  pinMode({p.Pin}, {(p.UseInternalPullup ? "INPUT_PULLUP" : "INPUT")}); // I{p.Index}");
            foreach (var p in outputPins)
                sb.AppendLine($"  pinMode({p.Pin}, OUTPUT); // Q{p.Index}");
            foreach (var p in pwmOutPins)
                sb.AppendLine($"  pinMode({p.Pin}, OUTPUT); // AO{p.Index} (PWM)");
            sb.AppendLine();
            sb.AppendLine("  // timer / counter presets pulled from the ladder rungs");
            foreach (var rung in program.Rungs)
            {
                foreach (var o in rung.Outputs)
                {
                    if (o.CoilType == CoilType.TimerOnDelay || o.CoilType == CoilType.TimerOffDelay)
                        sb.AppendLine($"  T[{o.OutputIndex}].preset = {o.Preset}; // ms");
                    if (o.CoilType == CoilType.CounterUp || o.CoilType == CoilType.CounterDown)
                        sb.AppendLine($"  C[{o.OutputIndex}].preset = {o.Preset};");
                }
            }
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("void loop() {");
            sb.AppendLine("  // 1) read physical / analog inputs");
            foreach (var p in inputPins)
                sb.AppendLine($"  I[{p.Index}] = digitalRead({p.Pin}) == HIGH;");
            foreach (var p in analogInPins)
                sb.AppendLine($"  AI[{p.Index}] = analogRead({p.Pin});");
            sb.AppendLine();

            sb.AppendLine("  // 2) evaluate rungs top to bottom, like a PLC scan");
            int rungNo = 0;
            foreach (var rung in program.Rungs)
            {
                rungNo++;
                sb.AppendLine(string.IsNullOrWhiteSpace(rung.Comment) ? $"  // Rung {rungNo}" : $"  // Rung {rungNo}: {rung.Comment}");
                string expr = BuildRungExpression(rung);
                sb.AppendLine($"  bool r{rungNo} = {expr};");
                foreach (var output in rung.Outputs)
                    sb.AppendLine(BuildCoilStatement(output, $"r{rungNo}", pwmOutPins));
                sb.AppendLine();
            }

            sb.AppendLine("  // 3) write physical / PWM outputs");
            foreach (var p in outputPins)
                sb.AppendLine($"  digitalWrite({p.Pin}, Q[{p.Index}] ? HIGH : LOW);");
            sb.AppendLine();
            sb.AppendLine("  // 4) report state to the app's Live Monitor over Serial (throttled)");
            sb.AppendLine("  if (millis() - lastStatePrint >= 150) {");
            sb.AppendLine("    lastStatePrint = millis();");
            sb.AppendLine("    printState();");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  delay(SCAN_DELAY_MS);");
            sb.AppendLine("}");
            sb.AppendLine();

            // ---- state printer for the Live Monitor tab ----
            sb.AppendLine("void printState() {");
            sb.AppendLine("  Serial.print(\"S,I=\");");
            AppendBoolArrayPrint(sb, "I", Math.Max(inputCount, 1));
            sb.AppendLine("  Serial.print(\",Q=\");");
            AppendBoolArrayPrint(sb, "Q", Math.Max(outputCount, 1));
            sb.AppendLine("  Serial.print(\",M=\");");
            AppendBoolArrayPrint(sb, "M", Math.Max(memoryCount, 1));
            sb.AppendLine("  Serial.print(\",T=\");");
            AppendStructArrayPrint(sb, "T", "q", Math.Max(timerCount, 1));
            sb.AppendLine("  Serial.print(\",C=\");");
            AppendStructArrayPrint(sb, "C", "q", Math.Max(counterCount, 1));
            sb.AppendLine("  Serial.println();");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void AppendBoolArrayPrint(StringBuilder sb, string arrName, int count)
        {
            sb.AppendLine($"  for (int i = 0; i < {count}; i++) Serial.print({arrName}[i] ? '1' : '0');");
        }

        private static void AppendStructArrayPrint(StringBuilder sb, string arrName, string field, int count)
        {
            sb.AppendLine($"  for (int i = 0; i < {count}; i++) Serial.print({arrName}[i].{field} ? '1' : '0');");
        }

        public static int SizeFor(LadderProgram program, AddressKind kind)
        {
            int max = -1;
            foreach (var p in program.PinMap.Where(p => p.Kind == kind))
                max = Math.Max(max, p.Index);
            foreach (var rung in program.Rungs)
            {
                foreach (var o in rung.Outputs)
                {
                    if (o.OutputKind == kind) max = Math.Max(max, o.OutputIndex);
                    if (kind == AddressKind.AnalogInput && o.CoilType == CoilType.AnalogOutput &&
                        o.AnalogSource == AnalogSource.CopyFromAnalogInput)
                        max = Math.Max(max, o.AnalogSourceIndex);
                    if (o.ResetIndex >= 0 && o.ResetKind == kind)
                        max = Math.Max(max, o.ResetIndex);
                }
                foreach (var b in rung.Branches)
                    foreach (var c in b.Contacts)
                        if (c.Kind == kind) max = Math.Max(max, c.Index);
            }
            return max + 1;
        }

        private static string RawExpr(AddressKind kind, int index)
        {
            switch (kind)
            {
                case AddressKind.Input: return $"I[{index}]";
                case AddressKind.Output: return $"Q[{index}]";
                case AddressKind.Memory: return $"M[{index}]";
                case AddressKind.Timer: return $"T[{index}].q";
                case AddressKind.Counter: return $"C[{index}].q";
                default: return "false";
            }
        }

        private static string ContactExpr(Contact c)
        {
            if (c.Kind == AddressKind.AnalogInput)
            {
                string op;
                switch (c.Operator)
                {
                    case ComparatorOp.GreaterThan: op = ">"; break;
                    case ComparatorOp.GreaterOrEqual: op = ">="; break;
                    case ComparatorOp.LessThan: op = "<"; break;
                    case ComparatorOp.LessOrEqual: op = "<="; break;
                    case ComparatorOp.Equal: op = "=="; break;
                    default: op = ">"; break;
                }
                string cmp = $"(AI[{c.Index}] {op} {c.Threshold})";
                return c.Mode == ContactMode.NormallyClosed ? $"!{cmp}" : cmp;
            }

            string raw = RawExpr(c.Kind, c.Index);
            return c.Mode == ContactMode.NormallyClosed ? $"!{raw}" : raw;
        }

        private static string BuildRungExpression(Rung rung)
        {
            var branchExprs = rung.Branches.Select(b =>
                b.Contacts.Count == 0 ? "false" : "(" + string.Join(" && ", b.Contacts.Select(ContactExpr)) + ")");
            return string.Join(" || ", branchExprs);
        }

        private static string TargetArray(AddressKind kind, int idx)
        {
            switch (kind)
            {
                case AddressKind.Output: return $"Q[{idx}]";
                case AddressKind.Memory: return $"M[{idx}]";
                default: return $"Q[{idx}]";
            }
        }

        private static string BuildCoilStatement(CoilOutput o, string resultVar, System.Collections.Generic.List<PinMapping> pwmOutPins)
        {
            int idx = o.OutputIndex;
            string resetExpr = o.ResetIndex >= 0 ? RawExpr(o.ResetKind, o.ResetIndex) : null;

            switch (o.CoilType)
            {
                case CoilType.Output:
                    return "  " + TargetArray(o.OutputKind, idx) + $" = {resultVar};";

                case CoilType.Set:
                    return $"  if ({resultVar}) {TargetArray(o.OutputKind, idx)} = true;";

                case CoilType.Reset:
                    return $"  if ({resultVar}) {TargetArray(o.OutputKind, idx)} = false;";

                case CoilType.TimerOnDelay:
                {
                    string body =
$@"  if ({resultVar}) {{
    if (!T[{idx}].running) {{ T[{idx}].running = true; T[{idx}].start = millis(); }}
    T[{idx}].q = (millis() - T[{idx}].start) >= T[{idx}].preset;
  }} else {{
    T[{idx}].running = false;
    T[{idx}].q = false;
  }}";
                    if (resetExpr != null)
                        body += $"\n  if ({resetExpr}) {{ T[{idx}].running = false; T[{idx}].q = false; }}";
                    return body;
                }

                case CoilType.TimerOffDelay:
                {
                    string body =
$@"  if ({resultVar}) {{
    T[{idx}].q = true;
    T[{idx}].offRunning = false;
  }} else {{
    if (!T[{idx}].offRunning) {{ T[{idx}].offRunning = true; T[{idx}].start = millis(); }}
    if ((millis() - T[{idx}].start) >= T[{idx}].preset) T[{idx}].q = false;
  }}";
                    if (resetExpr != null)
                        body += $"\n  if ({resetExpr}) {{ T[{idx}].q = false; T[{idx}].offRunning = false; }}";
                    return body;
                }

                case CoilType.CounterUp:
                {
                    string body =
$@"  if ({resultVar} && !C[{idx}].lastIn) {{ C[{idx}].count++; }}
  C[{idx}].lastIn = {resultVar};
  C[{idx}].q = C[{idx}].count >= C[{idx}].preset;";
                    if (resetExpr != null)
                        body += $"\n  if ({resetExpr}) {{ C[{idx}].count = 0; C[{idx}].q = false; }}";
                    return body;
                }

                case CoilType.CounterDown:
                {
                    string body =
$@"  if ({resultVar} && !C[{idx}].lastIn) {{ C[{idx}].count--; }}
  C[{idx}].lastIn = {resultVar};
  C[{idx}].q = C[{idx}].count <= 0;";
                    if (resetExpr != null)
                        body += $"\n  if ({resetExpr}) {{ C[{idx}].count = C[{idx}].preset; C[{idx}].q = false; }}";
                    return body;
                }

                case CoilType.AnalogOutput:
                {
                    string valueExpr = o.AnalogSource == AnalogSource.Constant
                        ? o.AnalogConstant.ToString()
                        : $"map(AI[{o.AnalogSourceIndex}], 0, 1023, 0, 255)";
                    var mapping = pwmOutPins.FirstOrDefault(p => p.Index == idx);
                    if (mapping == null)
                        return $"  // WARNING: AO{idx} has no pin mapped in the Pin Mapping tab - skipped";
                    return $"  analogWrite({mapping.Pin}, {resultVar} ? ({valueExpr}) : 0); // AO{idx}";
                }

                default:
                    return "  // unknown coil type";
            }
        }
    }
}
